version: '2'

services:
  db:
    image: postgres
  api:
    build:
      context: ./
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./:/income-management
    ports:
      - 3000:3000
    depends_on:
      - db
