default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password:

development:
  <<: *default
  database: income-management_development

test:
  <<: *default
  database: income-management_test

production:
  <<: *default
  database: income-management_production
  username: income-management
  password: <%= ENV['INCOME-MANAGEMENT_DATABASE_PASSWORD'] %>
